### ISSUE TITLE
Data using same key is overriden in JSON output

### ISSUE THREAD

**Issue by Gnejs** [SirWaddles/JohnWickParse#8]
Reproducable asset example: CollectionBookSections

There should be several sections with the same name (as referenced in CollectionBookPages)
E.g. : 3 "weapons_Melee_Spears" sections.
Since the key is the same the key:object entry is replaced and show the latest entry only.
Perhaps a hasKey() check can be done and convert the the key:object to key:array instead and append the new object to said array.

Exporting with FModel shows all the sections since they are exported differently.

Using it via CLI in an automated manner, I'll manually export from FModel for now for these specific files. 
Love the project, it's been really helpful in mining Save the world data. Thanks! :)

**Comment by SirWaddles** [comment]
While I realise it's maybe not ideal, duplicate keys are preserved in the internal model and the serialized json. I'm not sure what code you're using that would be removing them.

This is the serialized version of the file you're referring to:

![](https://genj.io/i/7f833958a82a.png)

My view is that there's not really an easy to way to solve this. The structure in the assets has duplicate keys, and there's not really a way to be consistent about guessing when to use an array and when not to - the only solution is to **always** use an array when there could maybe be duplicate keys. Otherwise, only using an array when theres >1 items would result in a pretty inconsistent schema.

So while it's maybe not the best solution, the current system seems to be the least worst option. It just may take some doing to make sure that code realises that there is non-standard stuff going on.

**Comment by Gnejs** [comment]
Hey, thanks for the reply, you are correct, the missing key:value sets are not due to the project, apparently the JSON formatter in Sublime is destructive and got rid of the duplicates..so yeah that was very unexpected. 😮 Sorry for the misinformation.

I'd still say that duplicate names is rather bad since JSON is not supposed to have them according to the specification, but if you feel like it is not worth the trouble that is fine. :)
I can just add a middle step to give the raw exported JSON some "massage"/sanity check to reformat it to correct JSON. As long as the exported data has all the information, which it has, I'm happy. :)

Thanks again, very helpful project! Feel free to close the issue if it is 'working as expected'.

Cheers!
